name: eslint

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: yarn install
        run: yarn install
      - name: Run eslint
        run: yarn lint
